# base directory of oxygen icon set checkout
OXYGEN = $(HOME)/src/oxygen-gitsvn
# extension icons
ICONS = \
	icon16.png \
	icon48.png \
	icon128.png

all: $(ICONS)

icon16.png:	$(OXYGEN)/16x16/places/bookmarks.png
	cp $< $@

icon48.png:	$(OXYGEN)/48x48/places/bookmarks.png
	cp $< $@

icon128.png:	$(OXYGEN)/128x128/places/bookmarks.png
	cp $< $@
